### PR TITLE
[pr] release version to 0.0.21

### PR DESCRIPTION
**Pull request by rryqszq4**

### CODE REVIEW

**Comment by rryqszq4** [comment]
Launch notification @joanhey

**Comment by joanhey** [comment]
Will be good if you add in the comment the change-log for any version.

**Comment by joanhey** [comment]
ngx_php7 0.0.21 changes:                                                            4 Nov 2019


- Add directive init_worker_by_php_block.
- Add directive rewrite_by_php_block.
- Add directive access_by_php_block.
- Add directive content_by_php_block.
- Add directive log_by_php_block.
- Add directive header_filter_by_php_block.
- Add directive body_by_php_block.
- Fixed support startup opcache, thanks joanhey.
- Optimize mysql driver.
- Optimize redis driver.

**Comment by rryqszq4** [comment]
> Will be good if you add in the comment the change-log for any version.
> So the people know it without need to check the chagelog.
> Also normally show in the releases page:
> https://github.com/rryqszq4/ngx_php7/releases

Accept~

**Pull request merged**
