### PR TITLE
Update redis

### PR DESCRIPTION
**Pull request by joanhey**
Add phpdoc to atributes.

Use bool in $isDebug

Use global namespace for performance ( 10-20% gain).

Unify debug. Format code.

### CODE REVIEW

**Comment by rryqszq4** [comment]
@joanhey I will merge the code, do you confirm it?

**Comment by joanhey** [comment]
It's ready to be merged.

**Comment by joanhey** [comment]
The problem with the unset() will exist in the mysql too.

**Comment by rryqszq4** [comment]
> The problem with the unset() will exist in the mysql too.

Mark, I will write a test case later.

**Pull request merged**
